language: go
go:
- '1.13.3'
go_import_path: github.com/signmykeyio/signmykey
env:
  - GO111MODULE=on GOPROXY=https://proxy.golang.org 
stages:
  - name: test
    if: tag IS blank
  - name: build pull request
    if: type == pull_request
  - name: build and package master
    if: branch = master AND type != pull_request
  - name: build and release tag
    if: tag IS present
  - name: site
    if: tag IS present
jobs:
  include:
  - stage: test
    name: lint
    script:
    - make lint_install
    - make lint
  - script:
    - make test
    name: unit testing
  - script:
    - make site_install
    - make site
    name: site build
  - stage: build pull request
    script:
    - make build
  - stage: build and package master
    sudo: required
    script:
    - make build VERSION=${TRAVIS_BUILD_NUMBER}
    - make fpm_install
    - make fpm VERSION=${TRAVIS_BUILD_NUMBER}
    - make fpm_upload_dev VERSION=${TRAVIS_BUILD_NUMBER}
    env:
    - GO111MODULE=on GOPROXY=https://proxy.golang.org 
    - secure: "oLSz73l95wWZgaSJcbdEr7fnvb381PQfMIvCY+yZXOhm+qf8lBbNCpyCUs/r1pP1OmXp7+FEsgBi1ah1OGuMCM/2usyvmBDMqw8sc7XYht4CL+OWS2NEgkhUIHwqlfGtD5/Y8jilDWkGOXUeWqleAo+m593aMz2cRe6SvsLbnJ2c+s2sXbvF92nwzL2u/l/g7pQppGlUzYlwTL/LG/YYlEuLw0X6qBdESCw3m3lZ1JbjpASK2hSJTirNX72ofr2V5XWfCGGDubKSNMiqGk6eT6AY4pg0WZjGvjRGu4Zmx/YjqMLBjuTtftOW+owR/LkmcTfQVr3N/g/Ev8hi1ymGsyEcn/DVLi7DHd9aDIq+/8YW7/ocJyEAPjgGapwNM4n+DFk5sWKDXCOmvn/3MgZS5O7OqhMDdSsJlzHQoARpWMzv/ycjSjLAdGHMFltIa/vwhIYqlvqHye4mHcgHEnSot7BLWc39t9RymF9wLLp/5dIGyorsC003uFHPzv8ZggvNk/IeKs4NzJUTp7As9vB0Zcbo0gbiJMLWUqSxH6QeApBGgt6/mTVjc0vcDj2/5VUb6IzYBV3VWFQJs3c/Zv6sTHaJHa7I5T/5ErMWgU0903fqL5/ilf4f9CB8UTxwckQB7VH+vL33ITVvqTUWGw5UxZDusUNg+daL62IQJvJtopU="
    - secure: "YZkbk5obX341PCx6GZsp0a35uqIqkbX0Ld1MeDYUZSoz1kCpGhgXyGw+jumaDxnVAKnijT/hxVavcd0YW18X6bLiBvWKpHvjucaxcetveAvf8EvmNmSRnsGNMXZcF8AbkWTjTpWpyszmLeF4SGAj6V3bIovcl6BCu8SqsN9Hlccs0AQ8fDrfWx2z/FAyUk125NOr6jJjLVftGdDvUb4iFv6l5xEHQTPkbJ25Fz9wxaiWNmaEFSiNoxql0BoKBMiagZDMvmarsN4kH0V5ttrA50JShIv+5Tx5JNng8/6CAktJ1cHONY8c1uIRrbXUyVWjZnxKtlFlZUebgyMpAgtrXPqVt0PCyh5KgkowWXoZ/61dY/M3lgFO8MK7LSes/BPDtiVhiMEGEgUtMPm5ShgUOaKTslVU13UGNXQRaCSgln9zDEtq0NT+SH1+mJRB6UmHzi6gDWiszfux0ILssnf33YhyxUdjNirWD15J5ZKl2kQ+UhRt/2ZFJqw7SBka3xJNzuREW4/oRbk8hHjRTlAC5sfIRLhwpJF3xmmy2pZqE+4nmjdkHF8WKc9F5CXumHZKpqP5EiLvWguOQucC/et871jRNzirT7OCiQv/xG1+weXdUk1vLriNPGqa6ZoWy9+i5HDRuHSFHQ0ihTQjitqx5JSy1BLKtlWx6QVn28Exau4="
  - stage: build and release tag
    sudo: required
    script:
    - make build VERSION=${TRAVIS_TAG}
    - make fpm_install
    - make fpm VERSION=${TRAVIS_TAG}
    - make fpm_upload_tag VERSION=${TRAVIS_TAG}
    env:
    - GO111MODULE=on GOPROXY=https://proxy.golang.org 
    - secure: "oLSz73l95wWZgaSJcbdEr7fnvb381PQfMIvCY+yZXOhm+qf8lBbNCpyCUs/r1pP1OmXp7+FEsgBi1ah1OGuMCM/2usyvmBDMqw8sc7XYht4CL+OWS2NEgkhUIHwqlfGtD5/Y8jilDWkGOXUeWqleAo+m593aMz2cRe6SvsLbnJ2c+s2sXbvF92nwzL2u/l/g7pQppGlUzYlwTL/LG/YYlEuLw0X6qBdESCw3m3lZ1JbjpASK2hSJTirNX72ofr2V5XWfCGGDubKSNMiqGk6eT6AY4pg0WZjGvjRGu4Zmx/YjqMLBjuTtftOW+owR/LkmcTfQVr3N/g/Ev8hi1ymGsyEcn/DVLi7DHd9aDIq+/8YW7/ocJyEAPjgGapwNM4n+DFk5sWKDXCOmvn/3MgZS5O7OqhMDdSsJlzHQoARpWMzv/ycjSjLAdGHMFltIa/vwhIYqlvqHye4mHcgHEnSot7BLWc39t9RymF9wLLp/5dIGyorsC003uFHPzv8ZggvNk/IeKs4NzJUTp7As9vB0Zcbo0gbiJMLWUqSxH6QeApBGgt6/mTVjc0vcDj2/5VUb6IzYBV3VWFQJs3c/Zv6sTHaJHa7I5T/5ErMWgU0903fqL5/ilf4f9CB8UTxwckQB7VH+vL33ITVvqTUWGw5UxZDusUNg+daL62IQJvJtopU="
    - secure: "YZkbk5obX341PCx6GZsp0a35uqIqkbX0Ld1MeDYUZSoz1kCpGhgXyGw+jumaDxnVAKnijT/hxVavcd0YW18X6bLiBvWKpHvjucaxcetveAvf8EvmNmSRnsGNMXZcF8AbkWTjTpWpyszmLeF4SGAj6V3bIovcl6BCu8SqsN9Hlccs0AQ8fDrfWx2z/FAyUk125NOr6jJjLVftGdDvUb4iFv6l5xEHQTPkbJ25Fz9wxaiWNmaEFSiNoxql0BoKBMiagZDMvmarsN4kH0V5ttrA50JShIv+5Tx5JNng8/6CAktJ1cHONY8c1uIRrbXUyVWjZnxKtlFlZUebgyMpAgtrXPqVt0PCyh5KgkowWXoZ/61dY/M3lgFO8MK7LSes/BPDtiVhiMEGEgUtMPm5ShgUOaKTslVU13UGNXQRaCSgln9zDEtq0NT+SH1+mJRB6UmHzi6gDWiszfux0ILssnf33YhyxUdjNirWD15J5ZKl2kQ+UhRt/2ZFJqw7SBka3xJNzuREW4/oRbk8hHjRTlAC5sfIRLhwpJF3xmmy2pZqE+4nmjdkHF8WKc9F5CXumHZKpqP5EiLvWguOQucC/et871jRNzirT7OCiQv/xG1+weXdUk1vLriNPGqa6ZoWy9+i5HDRuHSFHQ0ihTQjitqx5JSy1BLKtlWx6QVn28Exau4="
    deploy:
      provider: releases
      skip-cleanup: true
      api_key:
        secure: ZtPRK96VNHkJzwXMZ8BbYaU5JIkPvxJfeENjafaZ3PEx54oPwFcizypeiddr7S27ivvAavOvu9CJkhETiGINBkCxfwK5u4NXvR4l4fZiajUpb0zZ9GC9R79HeXhMZ9wGsJcfgF1xsxOISWdnXSBBRZpTbd2UiWgoYeSxGQ3THYOXturEZo110Zt9FKmOw37X0BK2Pa2A1kxsVVBKYhYsxhL6tQdhJZITakxmB/qCsYQ/O26IKb3NULLIS3SbI7K8J7rswUU3qtwSJyRoGNUlDei2PmONTCo9hNk/UEUE7N4D4qbdfHXtnOxTo3CI2KN3irzMRW6lHoCOfUeJjYxNdEgvzm4UAS5zP9uPynKMfWEV2zp35p3NWtrsjyYT7sCH7SmCimLIkTNw2S5Yfnk5uZHrhacTLsonfXzBLe2YpvP6ARYm+KctRVuzeRcEIKtjBmdPrLix9D3epoANyxK1BmiVOBotNEO1R1rOaPSdGNI9WhjbRNRun5GtIW0dRDKidH9UwOj0qeAU8FnJ5Pg3BXP8fRdvCo3QbQ/D7vIOqinvxRuiy7em4JCe2KF3TpkBqqbNwE4aoRDYzFBlMIFNwPTts6krSkuIcs0xBo+2plJB3ENlpLrC3lG4GoFu+N1gpATrHFwF/l/yLe46CSudZVJNq2DRsxEBqe159DH7B4s=
      file_glob: true
      file: bin/*.zip
      on:
        tags: true
  - stage: site
    script:
    - make site_install
    - make site
    deploy:
      provider: pages
      skip-cleanup: true
      local-dir: docs/public/
      repo: signmykeyio/signmykeyio.github.io
      target-branch: master
      fqdn: signmykey.io
      github-token:
        secure: ZtPRK96VNHkJzwXMZ8BbYaU5JIkPvxJfeENjafaZ3PEx54oPwFcizypeiddr7S27ivvAavOvu9CJkhETiGINBkCxfwK5u4NXvR4l4fZiajUpb0zZ9GC9R79HeXhMZ9wGsJcfgF1xsxOISWdnXSBBRZpTbd2UiWgoYeSxGQ3THYOXturEZo110Zt9FKmOw37X0BK2Pa2A1kxsVVBKYhYsxhL6tQdhJZITakxmB/qCsYQ/O26IKb3NULLIS3SbI7K8J7rswUU3qtwSJyRoGNUlDei2PmONTCo9hNk/UEUE7N4D4qbdfHXtnOxTo3CI2KN3irzMRW6lHoCOfUeJjYxNdEgvzm4UAS5zP9uPynKMfWEV2zp35p3NWtrsjyYT7sCH7SmCimLIkTNw2S5Yfnk5uZHrhacTLsonfXzBLe2YpvP6ARYm+KctRVuzeRcEIKtjBmdPrLix9D3epoANyxK1BmiVOBotNEO1R1rOaPSdGNI9WhjbRNRun5GtIW0dRDKidH9UwOj0qeAU8FnJ5Pg3BXP8fRdvCo3QbQ/D7vIOqinvxRuiy7em4JCe2KF3TpkBqqbNwE4aoRDYzFBlMIFNwPTts6krSkuIcs0xBo+2plJB3ENlpLrC3lG4GoFu+N1gpATrHFwF/l/yLe46CSudZVJNq2DRsxEBqe159DH7B4s=
      on:
        tags: true
